### ISSUE TITLE
Push notifications failed after upgrade to 6.15.X

### ISSUE THREAD

**Issue by Woozhb** [traccar/traccar#5996]
First of all, apologies if I get anything wrong. This is my first report, so I might not be doing it properly, I may be missing some information, or I could even be completely off.

I’ve just updated to the latest released version and, while testing notifications, one of the push notification tests on my phone failed. These two entries showed up in the log:

```text
2026-08-26 01:56:14 ERROR: Thread exception - jdk.net.Sockets - ClassNotFoundException (...)
2026-08-26 01:57:19 ERROR: Thread exception - Exception java.lang.NoClassDefFoundError: jdk/net/Sockets [in thread "httpclient-dispatch-1"] - ExceptionInInitializerError (...)
```

After looking into it a bit, I tried changing the Java runtime used to start the server and switched to the OpenJDK version included with Debian 13. I restarted the server and everything started working properly again.

With the version upgrade, Apache HttpClient 5.6 uses `jdk.net.Sockets` in its connection operator, but I believe Traccar ships with a reduced JRE built with `jlink`, including `java.se`, `jdk.charsets`, `jdk.crypto.ec` and `jdk.unsupported`, but **not `jdk.net`**.

For now I’ve been able to keep things running by switching Java versions and using Debian’s OpenJDK, but I’m not completely sure whether my diagnosis is actually correct.

**Comment by tananaev** [comment]
Which specific version?

**Comment by Woozhb** [comment]
6.15.1

**Comment by tananaev** [comment]
Have you tried upgrading? https://github.com/traccar/traccar/issues/5990

**Comment by Woozhb** [comment]
What you mean?? I just upgraded to current version, from here: https://github.com/traccar/traccar/releases/download/v6.15.1/traccar-linux-64-6.15.1.zip

**Comment by tananaev** [comment]
https://github.com/traccar/traccar/releases
