### ISSUE TITLE
How can I just use the server in linux CentOS 6.2 ??

### ISSUE THREAD

**Issue by hackerunet** [traccar/traccar#51]
Do you have a procedure to make the server work in a centos 6.2 linux server ??
I had read the documentation and it says that I need to install 3rd party libraries. So the thing is that I downloaded and unzip the server, but I received this error:
Exception in thread "main" java.lang.NoClassDefFoundError: tracker-server/jar
Caused by: java.lang.ClassNotFoundException: tracker-server.jar
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: tracker-server.jar. Program will exit.
