### ISSUE TITLE
Firebase push notifications broken on 6.15.1: NoClassDefFoundError: jdk/net/Sockets (bundled JRE 25 + Apache HttpClient5)

### ISSUE THREAD

**Issue by alecoud** [traccar/traccar#5990]
**Describe the bug**

After upgrading from 6.10.0 to 6.15.1 (Linux installer), Firebase Cloud Messaging notifications fail immediately on server start with a `NoClassDefFoundError: jdk/net/Sockets`. This crashes the async HTTP I/O reactor used internally by the Firebase Admin SDK, and every subsequent Firebase notification attempt fails with `IOReactorShutdownException` for the rest of the server's uptime (only fixed by a restart, which just repeats the same crash).

This appears to be a compatibility issue between Apache HttpClient5 (pulled in transitively via `com.google.firebase:firebase-admin`) and the bundled JRE 25 shipped with the Linux installer package, specifically when that JRE is built/trimmed via `jlink`. Apache HttpClient5's `ReflectionUtils` tries to access `jdk.net.Sockets` reflectively, which is not resolvable in this runtime.

Reference: same root-cause error reported in a different project using a jlink'd JDK 25 image: https://github.com/jenkinsci/docker-agents/issues/1124

**To Reproduce**

1. Install Traccar 6.15.1 via the official Linux installer (`traccar-linux-64-latest.zip` → `traccar.run`)
2. Configure Firebase notifications (`notificator.firebase.*` in `traccar.xml`)
3. Start the server and trigger any event that sends a Firebase push notification (e.g. a device coming online, ignition event, alarm)

**Expected behavior**

Firebase notification sends successfully via HTTPS to `fcm.googleapis.com`.

**Actual behavior / stack trace**
2026-08-24 00:20:01 ERROR: Thread exception -
java.lang.NoClassDefFoundError: jdk/net/Sockets
at org.apache.hc.core5.util.ReflectionUtils.<clinit>(ReflectionUtils.java:41)
at org.apache.hc.core5.reactor.SingleCoreIOReactor.prepareSocket(SingleCoreIOReactor.java:312)
at org.apache.hc.core5.reactor.SingleCoreIOReactor.processConnectionRequest(SingleCoreIOReactor.java:378)
at org.apache.hc.core5.reactor.SingleCoreIOReactor.processPendingConnectionRequests(SingleCoreIOReactor.java:355)
at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:151)
at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:92)
at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.ClassNotFoundException: jdk.net.Sockets
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
... 8 more

After this, every subsequent Firebase send attempt fails with:
com.google.firebase.messaging.FirebaseMessagingException: Unknown error while making a remote service call: Unknown exception in request
Caused by: java.io.IOException: Unknown exception in request
Caused by: java.util.concurrent.ExecutionException: org.apache.hc.core5.reactor.IOReactorShutdownException: I/O reactor has been shut down

**Environment**

- Traccar version: 6.15.1
- Install method: official Linux installer (`traccar-linux-64-6.15.1.zip`)
- Bundled JRE: OpenJDK 64-Bit Server VM, Eclipse Adoptium, `25.0.4+7-LTS`
- OS: Ubuntu 22.04
- Database: PostgreSQL 14 + TimescaleDB (unrelated to this issue — confirmed same error also occurs independent of DB backend, since it happens on server thread startup unrelated to any DB call)

**Additional context**

This is reproducible on both an in-place upgrade (6.10.0 → 6.15.1) and a completely fresh install of 6.15.1, so it's not related to migration state — it's the bundled JRE itself.

Not sure if the fix belongs in Traccar's build (e.g. pinning a full non-jlink'd JRE, or excluding `jdk.net` trimming) or upstream in Apache HttpClient5 — flagging here since it affects the officially distributed Linux package.

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar/commit/53e3bb90888ae61b94128782f08e23d2c72f50f3.
